@isTest
public class ExecDashboardStatisticsControllerTests 
{
    /*
    static testMethod void GetTotalComplaintsAllTimeTest()
    {
         //Arrange
        integer expected = 0;

        //Act
        Test.startTest();
        integer actual = ExecutiveDashboardStatisticsController.GetTotalComplaintsAllTime('All', '2019');
        Test.stopTest();
        
        //Assert
        System.assertEquals(expected, actual); 
    }

    static testMethod void GetOpenComplaintsAllTimeTest()
    {
        //Arrange
        integer expected = 2;

        //Act
        Test.startTest();
        List<string> actual = ExecutiveDashboardStatisticsController.GetOpenComplaintsAllTime('All', '2019');
        Test.stopTest();
        
        //Assert
        System.assertEquals(expected, actual.size()); 
    }

    static testMethod void GetReferredComplaintsAllTimeTest()
    {
        //Arrange
        integer expected = 2;

        //Act
        Test.startTest();
        List<string> actual = ExecutiveDashboardStatisticsController.GetReferredComplaintsAllTime('All', '2019');
        Test.stopTest();
        
        //Assert
        System.assertEquals(expected, actual.size()); 
    }

    static testMethod void GetClosedComplaintsAllTimeTest()
    {
        //Arrange
        integer expected = 2;

        //Act
        Test.startTest();
        List<string> actual = ExecutiveDashboardStatisticsController.GetClosedComplaintsAllTime('All', '2019');
        Test.stopTest();
        
        //Assert
        System.assertEquals(expected, actual.size()); 
    }
    
       static testMethod void GetTotalComplaintsAllTimeBDOTest()
    {
         //Arrange
        integer expected = 0;

        //Act
        Test.startTest();
        integer actual = ExecutiveDashboardStatisticsController.GetTotalComplaintsAllTime('Air', '2019');
        Test.stopTest();
        
        //Assert
        System.assertEquals(expected, actual); 
    }

    static testMethod void GetOpenComplaintsAllTimeBDOTest()
    {
        //Arrange
        integer expected = 2;

        //Act
        Test.startTest();
        List<string> actual = ExecutiveDashboardStatisticsController.GetOpenComplaintsAllTime('Air', '2019');
        Test.stopTest();
        
        //Assert
        System.assertEquals(expected, actual.size()); 
    }

    static testMethod void GetReferredComplaintsAllTimeBDOTest()
    {
        //Arrange
        integer expected = 2;

        //Act
        Test.startTest();
        List<string> actual = ExecutiveDashboardStatisticsController.GetReferredComplaintsAllTime('Air', '2019');
        Test.stopTest();
        
        //Assert
        System.assertEquals(expected, actual.size()); 
    }

    static testMethod void GetClosedComplaintsAllTimeBDOTest()
    {
        //Arrange
        integer expected = 2;

        //Act
        Test.startTest();
        List<string> actual = ExecutiveDashboardStatisticsController.GetClosedComplaintsAllTime('Air', '2019');
        Test.stopTest();
        
        //Assert
        System.assertEquals(expected, actual.size()); 
    }
    */
}