@isTest()
public class GeoLocation_test2 {
    //public static testMethod void myUnitTest(){
      //  test.startTest();
       // List<Complaints__c> complaints = new List<Complaints__c>();
       // Complaints__c c = new Complaints__c();
       // c.Air__c = true;
       // c.Complaint_Location_Address__c = '1001 I Street';
       // c.Complaint_Location_City__c = 'Sacramento'; 
       // c.Complaint_Location_State__c = 'CA';
       // c.Complaint_Location_Zip_Code__c = '95812';
       // complaints.add(c);
       // insert complaints;
        
        //GeoLocation geoloc = new GeoLocation();
        //geoloc.geoLocationUpdate(complaints,true);
        //geoloc.geoLocationUpdate(complaints,false);
        
       // test.stopTest();
    //}
}